apiVersion: v2
name: sigstack
description: Helm chart for running all of our sigstore goodies (rekor, fulcio, trillian,  
type: application

version: 0.1.0

appVersion: "0.1.0"

dependencies:
- name: rekor
  version: "0.3.12"
  repository: "https://sigstore.github.io/helm-charts"
  condition: rekor.enabled
- name: fulcio
  version: "0.4.8"
  repository: "https://sigstore.github.io/helm-charts"
  condition: fulcio.enabled
- name: dex
  version: "0.9.0"
  repository: "https://charts.dexidp.io"
  condition: dex.enabled
